_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
        python_version: 3.11.1
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 7
                - 13
                - 16
                - 23
                - 38
                - 55
            "4": 3.11.1
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
architecture:
    value: Transformers
dataset:
    value: production_comments-txt
